# Generated by Django 3.1.8 on 2021-05-03 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_webpagegalleryimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='slogan',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
